### ISSUE TITLE
Create : Contact Us Page

### ISSUE THREAD

**Issue by Iseluin** [ReCoded-Org/capstone-IQLBPS-Dilmun#18]
## Summary

Users should be able to e-mail us with their problems and desires. Create a controlled form with validation schemas added. Sending e-mail functionality will be added later.

Design and responsiveness must be readied with Tailwind, snapshot/unit tests should also be written.

### Screenshots
![contact us](https://user-images.githubusercontent.com/63947758/197251556-62643592-ccc1-4e7f-8224-8cd0acad0c65.png)
![contact us 2 png ](https://user-images.githubusercontent.com/63947758/197251560-9d45d033-0e64-4683-81fa-9941f91a1b53.png)
![contact us 3](https://user-images.githubusercontent.com/63947758/197251562-baa0435a-895c-436d-aa87-262a2a35a79f.png)

### Basic example

N/A

### Motivation

It's always good to get some feedback from users.

**Comment by asaad-abughazaleh** [comment]
Ok sir Sent from Mail for Windows From: Kutay Kağan ÖzenSent: Monday, October 31, 2022 5:52 PMTo: ReCoded-Org/capstone-IQLBPS-DilmunCc: Asaad AbuGhazaleh; AssignSubject: Re: [ReCoded-Org/capstone-IQLBPS-Dilmun] Create : Contact Us Page (Issue #18) Assigned #18 to @asaad-abughazaleh.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
